### PR TITLE
chore: requirement updates

### PR DESCRIPTION
**Pull request by rayzhou-bit**
Ran the following commands locally:
`make upgrade`
`make test`

`make upgrade` updated the various requirements to the latest version. This introduced various errors and warnings when running `make test`.

I corrected the following pylint errors and warnings:
E0015 (unrecognized-option)
W0012 (unknown-option-value)
R0022 (useless-option-value)
C3001 (unnecessary-lambda-assignment)
E4702 (modified-iterating-dict)

### CODE REVIEW

**Comment by connorhaugh** [comment]
Can you inform as to what you did to verify these upgrades?

**Comment by rayzhou-bit** [comment]
I ran `make upgrade` locally which seems to be what the CI was trying to do. It's not passing for tests right now though. Trying to figure this out.

**Comment by bszabo** [comment]
Could you please enter a comment in this PR that documents which dependency's change you're responding to, what the nature of the breaking change was, and your general approach to resolving it?

**Comment by rayzhou-bit** [comment]
@bszabo I believe everything that broke was related to pylint. I went through the test/lint errors one by one. A large number of the them were deprecated options. For other errors, I modeled code changes after examples in pylint documentation, such as https://pylint.pycqa.org/en/latest/user_guide/messages/convention/unnecessary-lambda-assignment.html . I could have had them ignored, but it feels like it would be better to update.

**Comment by rayzhou-bit** [comment]
@bszabo I believe everything that broke was related to pylint. I went through the test/lint errors one by one. A large number of the them were deprecated options. For other errors, I modeled code changes after examples in pylint documentation, such as https://pylint.pycqa.org/en/latest/user_guide/messages/convention/unnecessary-lambda-assignment.html . I could have had them ignored, but it feels like it would be better to update.

**Pull request merged**
